github_intelligence:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'GITHUB_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'GITHUB_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'GITHUB_WH') }}"
      schema: RAW_GITHUB
      threads: 4
